import type { Metadata } from "next";
import localFont from "next/font/local";
import "./input.css";
import { Toaster } from "react-hot-toast";
import { ReduxProvider } from "@/providers/ReduxProvider";
import Providers from "@/providers/Providers";

const iranYekan = localFont({
  src: [
    {
      path: '../public/fonts/iranYekan/Qs_Iranyekan_thin.ttf',
      weight: '200',
      style: 'normal'
    },
    {
      path: '../public/fonts/iranYekan/Qs_Iranyekan_light.ttf',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../public/fonts/iranYekan/Qs_Iranyekan.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../public/fonts/iranYekan/Qs_Iranyekan_medium.ttf',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../public/fonts/iranYekan/Qs_Iranyekan_bold.ttf',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../public/fonts/iranYekan/Qs_Iranyekan_extrabold.ttf',
      weight: '700',
      style: 'normal'
    },
  ],
  variable: '--font-iranyekan'
});

export const metadata: Metadata = {
  title: "Akhavan shop",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={iranYekan.className}>
      <body className="bg-gradient-to-br from-gray-800 to-slate-900 text-white min-h-screen">
        <Providers>
          {children}
        </Providers>
        <Toaster toastOptions={{
          className: "!bg-gray-100 !text-black"
        }} />
      </body>
    </html>
  );
}
